
import React from 'react';
import { Question, QuestionType } from '../types';
import { ArrowLeft, Printer, Download, Book } from 'lucide-react';

interface ExamExportViewProps {
  questions: Question[];
  onBack: () => void;
  subjectName: string;
}

const ExamExportView: React.FC<ExamExportViewProps> = ({ questions, onBack, subjectName }) => {
  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="max-w-4xl mx-auto mt-8 px-6 pb-20 fade-in">
      <div className="flex items-center justify-between mb-8 no-print">
        <button 
            onClick={onBack}
            className="flex items-center gap-2 text-text-secondary hover:text-white px-4 py-2 rounded-xl transition-all active:scale-95 text-sm font-medium"
        >
            <ArrowLeft className="w-4 h-4" />
            Back to Results
        </button>
        <button 
            onClick={handlePrint}
            className="flex items-center gap-2 px-5 py-2.5 bg-primary text-white hover:bg-primaryHover rounded-xl font-bold shadow-lg transition-all active:scale-95"
        >
            <Printer className="w-4 h-4" />
            Print / Save PDF
        </button>
      </div>

      <div id="printable-exam" className="glass-panel rounded-2xl p-8 md:p-12 shadow-2xl bg-white text-black relative">
        <div className="text-center mb-12 border-b-2 border-black pb-6">
            <h1 className="text-4xl font-black mb-2 uppercase tracking-tighter">Mock Exam Paper</h1>
            <p className="text-xl font-bold text-gray-700">{subjectName}</p>
            <div className="mt-4 flex justify-between text-xs font-mono text-gray-500">
                <span>Total Questions: {questions.length}</span>
                <span>Generated by ExamWarp AI</span>
                <span>Date: {new Date().toLocaleDateString()}</span>
            </div>
        </div>

        <div className="space-y-12">
            {questions.map((q, idx) => (
                <div key={q.id} className="pb-8 border-b border-gray-100 last:border-0">
                    <div className="flex gap-4 mb-4">
                        <span className="font-bold text-lg min-w-[2rem]">{idx + 1}.</span>
                        <div className="flex-1">
                            <p className="text-lg font-medium leading-relaxed mb-4">{q.text}</p>
                            
                            {q.type === QuestionType.MCQ && q.options && (
                                <div className="grid grid-cols-1 md:grid-cols-2 gap-4 ml-2">
                                    {q.options.map((opt, oIdx) => (
                                        <div key={oIdx} className="flex gap-3 items-start">
                                            <span className="font-bold text-gray-400">{String.fromCharCode(65 + oIdx)}.</span>
                                            <span className="text-gray-800">{opt}</span>
                                        </div>
                                    ))}
                                </div>
                            )}
                        </div>
                    </div>

                    <div className="mt-6 p-4 bg-gray-50 rounded-lg border border-gray-200">
                        <div className="text-[10px] font-black uppercase text-gray-400 tracking-widest mb-2">Answer Key & Explanation</div>
                        <p className="text-sm font-bold text-black mb-2">
                            Correct Answer: {q.type === QuestionType.MCQ ? `${String.fromCharCode(65 + (q.correctAnswerIndex || 0))}` : 'See Explanation'}
                        </p>
                        <p className="text-sm text-gray-600 leading-relaxed italic">
                            {q.explanation}
                        </p>
                        {q.type !== QuestionType.MCQ && q.modelAnswer && (
                            <div className="mt-2 pt-2 border-t border-gray-200">
                                <span className="text-xs font-bold block text-gray-500 mb-1">Model Solution:</span>
                                <p className="text-sm text-gray-700">{q.modelAnswer}</p>
                            </div>
                        )}
                    </div>
                </div>
            ))}
        </div>

        <div className="mt-12 pt-6 border-t border-gray-300 text-center text-[10px] text-gray-400 uppercase tracking-[0.3em]">
            End of Document • ExamWarp Intelligence Engine
        </div>
      </div>
      
      <style>{`
        @media print {
            body { background: white !important; color: black !important; }
            .no-print { display: none !important; }
            .glass-panel { background: white !important; border: none !important; box-shadow: none !important; color: black !important; }
            #printable-exam { padding: 0 !important; }
        }
      `}</style>
    </div>
  );
};

export default ExamExportView;
