import React from 'react';
import { ArrowLeft, Book, Download, Printer } from 'lucide-react';

interface SummaryViewProps {
  summaryMarkdown: string;
  onBack: () => void;
}

const SummaryView: React.FC<SummaryViewProps> = ({ summaryMarkdown, onBack }) => {
  const handleDownload = () => {
    // Uses browser native print to save as PDF. 
    // The @media print styles in index.html ensure only the summary is visible.
    window.print();
  };

  return (
    <div className="max-w-4xl mx-auto mt-8 px-6 pb-20 fade-in">
      <div className="flex items-center justify-between mb-8 no-print">
        <button 
            onClick={onBack}
            className="flex items-center gap-2 text-text-secondary hover:text-white hover:bg-white/10 px-4 py-2 rounded-xl transition-all active:scale-95 duration-200 text-sm font-medium"
        >
            <ArrowLeft className="w-4 h-4" />
            Back to Dashboard
        </button>
        <div className="flex items-center gap-3">
            <button 
                onClick={handleDownload}
                className="flex items-center gap-2 px-5 py-2.5 bg-white text-black hover:bg-slate-200 rounded-xl font-bold shadow-lg transition-all active:scale-95 duration-200" 
                title="Download Summary PDF"
            >
                <Download className="w-4 h-4" />
                <span>Download PDF</span>
            </button>
        </div>
      </div>

      <div id="printable-summary" className="glass-panel rounded-2xl p-8 md:p-16 shadow-2xl relative overflow-hidden">
        {/* Print Only Header */}
        <div className="hidden print:block text-center mb-8 border-b-2 border-black pb-4">
             <h1 className="text-3xl font-bold text-black">ExamWarp AI Summary</h1>
             <p className="text-sm text-gray-600">Generated Study Material</p>
        </div>

        <div className="flex items-center gap-4 mb-10 pb-8 border-b border-white/10 no-print">
            <div className="w-14 h-14 bg-gradient-to-br from-violet-600 to-indigo-600 rounded-2xl flex items-center justify-center shadow-lg shadow-violet-500/20">
                <Book className="w-7 h-7 text-white" />
            </div>
            <div>
                <h1 className="text-3xl font-bold text-white mb-1">Smart Summary</h1>
                <p className="text-text-secondary text-base">AI-generated comprehensive review of your material.</p>
            </div>
        </div>

        <article className="prose prose-invert prose-lg max-w-none prose-headings:text-white prose-p:text-slate-300 prose-strong:text-violet-200 prose-li:text-slate-300 prose-blockquote:border-l-violet-500 prose-blockquote:bg-white/5 prose-blockquote:py-2 prose-blockquote:px-4 prose-blockquote:rounded-r-lg">
            <div className="whitespace-pre-wrap font-sans leading-relaxed">
                {summaryMarkdown}
            </div>
        </article>

        {/* Print Footer */}
        <div className="hidden print:block mt-8 pt-4 border-t border-gray-300 text-center text-xs text-gray-500">
            Generated by ExamWarp AI
        </div>
      </div>
    </div>
  );
};

export default SummaryView;